CREATE TABLE EmployeeFeedback (
    EmployeeID INT,
    SurveyDate DATETIME,
    Feedback VARCHAR(255),
    SatisfactionScore INT,
    SentimentAnalysis VARCHAR(255)
);

INSERT INTO EmployeeFeedback VALUES (15, '2023-11-09', 'support workload training opportunities growth deadlines team improvement', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (1, '2020-11-22', 'team management growth opportunities workload support', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (16, '2022-08-27', 'support growth team deadlines improvement training challenging management workload', 'Low', 'Negative');
INSERT INTO EmployeeFeedback VALUES (42, '2021-04-01', 'deadlines challenging growth support training improvement team', 'High', 'Negative');
INSERT INTO EmployeeFeedback VALUES (20, '2020-12-28', 'team opportunities workload management deadlines training', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (10, '2020-05-16', 'growth workload team opportunities deadlines management', 'Moderate', 'Positive');
INSERT INTO EmployeeFeedback VALUES (11, '2023-11-25', 'deadlines workload growth opportunities team management improvement support challenging training', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (36, '2023-01-13', 'management growth challenging training improvement support team deadlines opportunities workload', 'Low', 'Negative');
INSERT INTO EmployeeFeedback VALUES (43, '2022-11-22', 'workload deadlines management growth challenging improvement', 'Low', 'Negative');
INSERT INTO EmployeeFeedback VALUES (26, '2020-05-23', 'opportunities training improvement challenging workload growth management deadlines support', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (33, '2023-11-23', 'training deadlines workload opportunities challenging management growth', 'Low', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (31, '2021-03-22', 'management workload team challenging improvement opportunities growth training support', 'Moderate', 'Positive');
INSERT INTO EmployeeFeedback VALUES (36, '2023-10-04', 'growth deadlines workload team challenging training support improvement management opportunities', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (20, '2020-11-14', 'improvement support training opportunities management challenging deadlines team workload', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (32, '2022-07-29', 'support opportunities management improvement growth deadlines workload', 'Low', 'Negative');
INSERT INTO EmployeeFeedback VALUES (48, '2021-03-17', 'improvement growth opportunities challenging training team support workload management', 'High', 'Positive');
INSERT INTO EmployeeFeedback VALUES (2, '2020-10-29', 'management growth team training opportunities improvement workload support', 'High', 'Negative');
INSERT INTO EmployeeFeedback VALUES (47, '2020-08-28', 'management challenging growth support improvement deadlines training', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (6, '2022-07-16', 'growth improvement support training management team deadlines', 'Moderate', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (1, '2023-05-11', 'training challenging growth improvement team deadlines', 'Moderate', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (48, '2020-08-16', 'training management workload support team deadlines opportunities challenging', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (1, '2023-04-23', 'opportunities workload growth challenging training', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (27, '2020-05-30', 'opportunities improvement management growth challenging deadlines training team', 'Low', 'Negative');
INSERT INTO EmployeeFeedback VALUES (36, '2023-09-16', 'management deadlines improvement training workload support challenging growth', 'High', 'Negative');
INSERT INTO EmployeeFeedback VALUES (40, '2020-03-09', 'workload challenging management growth improvement team', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (10, '2020-07-16', 'challenging team growth training support management opportunities', 'Moderate', 'Positive');
INSERT INTO EmployeeFeedback VALUES (23, '2021-07-03', 'improvement deadlines opportunities team growth challenging support management workload training', 'Moderate', 'Positive');
INSERT INTO EmployeeFeedback VALUES (42, '2020-02-22', 'training team opportunities growth management support workload deadlines', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (10, '2023-11-15', 'training deadlines workload challenging management growth', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (9, '2021-08-12', 'challenging deadlines support training opportunities growth workload', 'Low', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (2, '2023-08-03', 'team training opportunities growth challenging deadlines workload support improvement management', 'Low', 'Negative');
INSERT INTO EmployeeFeedback VALUES (13, '2020-09-14', 'opportunities support training workload challenging deadlines management growth', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (38, '2020-07-12', 'support improvement team growth challenging training workload opportunities deadlines', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (31, '2020-12-26', 'support team improvement deadlines management', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (1, '2022-10-13', 'growth team management opportunities improvement deadlines training', 'Moderate', 'Positive');
INSERT INTO EmployeeFeedback VALUES (2, '2023-09-10', 'opportunities support improvement deadlines challenging team growth workload', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (23, '2023-02-24', 'deadlines management training workload improvement support team growth opportunities challenging', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (24, '2021-12-07', 'improvement training opportunities challenging growth management deadlines', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (3, '2023-07-31', 'training challenging improvement support management workload growth deadlines opportunities team', 'Low', 'Negative');
INSERT INTO EmployeeFeedback VALUES (17, '2023-05-15', 'opportunities support deadlines challenging improvement training workload team management growth', 'High', 'Negative');
INSERT INTO EmployeeFeedback VALUES (18, '2021-10-08', 'opportunities challenging team management deadlines improvement training growth support', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (17, '2022-04-21', 'improvement challenging management team growth workload support training', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (20, '2020-05-20', 'training team management improvement challenging deadlines growth opportunities workload support', 'High', 'Negative');
INSERT INTO EmployeeFeedback VALUES (31, '2022-06-20', 'improvement team support management challenging deadlines training opportunities', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (1, '2022-02-03', 'training growth opportunities management deadlines team workload challenging support improvement', 'High', 'Negative');
INSERT INTO EmployeeFeedback VALUES (21, '2023-11-17', 'support workload growth training team management improvement', 'High', 'Positive');
INSERT INTO EmployeeFeedback VALUES (23, '2020-02-25', 'challenging support growth opportunities workload deadlines team', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (29, '2021-10-26', 'team challenging deadlines management opportunities support improvement workload training growth', 'High', 'Positive');
INSERT INTO EmployeeFeedback VALUES (9, '2023-06-15', 'opportunities growth improvement deadlines support training management challenging workload team', 'High', 'Positive');
INSERT INTO EmployeeFeedback VALUES (50, '2023-12-30', 'support opportunities growth deadlines management workload', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (28, '2020-02-09', 'deadlines training team support opportunities growth challenging improvement workload', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (47, '2021-02-09', 'support deadlines workload opportunities growth', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (28, '2023-01-17', 'support training growth opportunities challenging team management', 'Moderate', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (33, '2022-06-02', 'team workload deadlines support improvement opportunities', 'Low', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (23, '2021-03-05', 'improvement opportunities training management challenging support workload growth', 'Moderate', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (49, '2022-07-19', 'growth deadlines opportunities workload team management support', 'High', 'Negative');
INSERT INTO EmployeeFeedback VALUES (36, '2022-05-26', 'challenging support training improvement management growth', 'High', 'Negative');
INSERT INTO EmployeeFeedback VALUES (48, '2021-01-12', 'team support improvement training growth challenging workload', 'Moderate', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (35, '2021-09-07', 'training opportunities deadlines management team growth challenging support', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (47, '2020-07-14', 'deadlines team opportunities management challenging improvement workload', 'High', 'Negative');
INSERT INTO EmployeeFeedback VALUES (50, '2022-07-07', 'management improvement support training workload opportunities growth team deadlines', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (38, '2020-04-15', 'management workload team challenging support improvement training deadlines', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (37, '2020-05-03', 'team opportunities support management improvement challenging growth workload training deadlines', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (50, '2022-01-05', 'deadlines team workload support challenging management improvement opportunities', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (17, '2023-05-03', 'growth support challenging opportunities deadlines team management training improvement workload', 'Low', 'Negative');
INSERT INTO EmployeeFeedback VALUES (10, '2021-10-04', 'management improvement challenging support deadlines', 'High', 'Negative');
INSERT INTO EmployeeFeedback VALUES (19, '2020-03-13', 'opportunities challenging deadlines training support growth management workload improvement team', 'High', 'Positive');
INSERT INTO EmployeeFeedback VALUES (43, '2021-07-25', 'training opportunities deadlines team improvement support workload management growth challenging', 'Moderate', 'Positive');
INSERT INTO EmployeeFeedback VALUES (32, '2020-10-05', 'training workload growth support improvement management', 'Moderate', 'Positive');
INSERT INTO EmployeeFeedback VALUES (39, '2022-12-22', 'growth team training management workload deadlines', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (30, '2020-06-29', 'deadlines workload growth support management challenging training', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (5, '2022-04-07', 'challenging support deadlines workload training improvement management growth', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (40, '2020-04-18', 'opportunities support workload challenging growth team management', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (9, '2023-04-19', 'team growth improvement management workload', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (19, '2021-10-31', 'improvement challenging opportunities support deadlines training management team', 'High', 'Positive');
INSERT INTO EmployeeFeedback VALUES (2, '2023-05-22', 'deadlines team improvement training challenging', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (34, '2020-08-30', 'support opportunities improvement training challenging growth team workload', 'Low', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (3, '2022-11-13', 'growth challenging management improvement opportunities support training team workload', 'High', 'Negative');
INSERT INTO EmployeeFeedback VALUES (16, '2021-08-27', 'support team growth opportunities management deadlines challenging workload training improvement', 'Low', 'Negative');
INSERT INTO EmployeeFeedback VALUES (17, '2020-01-22', 'challenging team support deadlines training workload growth', 'Moderate', 'Positive');
INSERT INTO EmployeeFeedback VALUES (2, '2021-03-11', 'training workload opportunities deadlines growth management', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (41, '2020-03-21', 'challenging training improvement management growth team workload deadlines opportunities support', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (37, '2020-07-13', 'growth deadlines management support improvement team', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (48, '2020-10-17', 'workload improvement training support growth opportunities team', 'Moderate', 'Positive');
INSERT INTO EmployeeFeedback VALUES (38, '2020-08-14', 'challenging management team growth support deadlines workload improvement', 'High', 'Positive');
INSERT INTO EmployeeFeedback VALUES (8, '2021-03-12', 'improvement management workload opportunities challenging support training', 'Moderate', 'Positive');
INSERT INTO EmployeeFeedback VALUES (5, '2022-08-15', 'challenging support management deadlines training', 'High', 'Positive');
INSERT INTO EmployeeFeedback VALUES (24, '2020-12-09', 'training opportunities growth deadlines workload management support', 'High', 'Positive');
INSERT INTO EmployeeFeedback VALUES (36, '2020-01-12', 'challenging workload deadlines management improvement growth support team', 'High', 'Negative');
INSERT INTO EmployeeFeedback VALUES (4, '2020-02-20', 'support challenging growth workload opportunities management improvement deadlines team', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (16, '2020-06-15', 'deadlines team training workload management support improvement growth challenging', 'High', 'Positive');
INSERT INTO EmployeeFeedback VALUES (29, '2023-05-10', 'team training support opportunities improvement challenging workload deadlines growth', 'Low', 'Positive');
INSERT INTO EmployeeFeedback VALUES (6, '2023-02-28', 'opportunities support deadlines workload growth training improvement team challenging management', 'Moderate', 'Negative');
INSERT INTO EmployeeFeedback VALUES (14, '2022-10-28', 'opportunities team training growth management improvement workload support challenging deadlines', 'High', 'Positive');
INSERT INTO EmployeeFeedback VALUES (7, '2022-04-10', 'deadlines team challenging management support opportunities improvement', 'Moderate', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (28, '2023-05-19', 'growth support team training workload management opportunities improvement', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (22, '2023-06-19', 'support team improvement growth challenging workload', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (21, '2020-12-17', 'challenging support training workload growth', 'High', 'Positive');
INSERT INTO EmployeeFeedback VALUES (35, '2020-06-13', 'training challenging opportunities support workload deadlines management team', 'High', 'Neutral');
INSERT INTO EmployeeFeedback VALUES (24, '2020-06-13', 'deadlines challenging improvement growth workload', 'Moderate', 'Neutral');
